# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Sledge-Plugin-TmplParamsBinder
version:      0.01
version_from: lib/Sledge/Plugin/TmplParamsBinder.pm
installdirs:  site
requires:
    PadWalker:                     1
    Test::More:                    0.32

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
